
--To CREATE a dababase 
IF NOT EXISTS (SELECT * FROM master..sysdatabases WHERE name='AMCIBdb')
CREATE DATABASE [AMCIBdb]
GO

USE [AMCIBdb]
GO
--After this please select this database from above dropdown list instead master
IF OBJECT_ID('tbl_ITEM_DETAILS') IS NOT NULL
DROP TABLE tbl_ITEM_DETAILS
GO

IF OBJECT_ID('tbl_ITEM_HISTORY') IS NOT NULL
DROP TABLE tbl_ITEM_HISTORY
GO

IF OBJECT_ID('tbl_STORE') IS NOT NULL
DROP TABLE tbl_STORE
GO

IF OBJECT_ID('tbl_REPAIR_STATUS') IS NOT NULL
DROP TABLE tbl_REPAIR_STATUS
GO

CREATE TABLE tbl_STORE
(
[StoreId] VARCHAR(10) CONSTRAINT pk_StoreId PRIMARY KEY,
[NAME] VARCHAR(50) NOT NULL
)
GO

CREATE TABLE tbl_REPAIR_STATUS
(
[REPAIRCODE] INT CONSTRAINT pk_RepaireCode PRIMARY KEY,
[REPAIRSTATUS] VARCHAR(100) NOT NULL
)
GO


CREATE TABLE tbl_ITEM_DETAILS
(
[SINO] VARCHAR(40) CONSTRAINT pk_SI PRIMARY KEY,
[DESCRIPTION] VARCHAR(100) NOT NULL,
[MAKEANDMODEL] VARCHAR(100) NOT NULL,
[STOREID] VARCHAR(10) CONSTRAINT fk_storeid REFERENCES tbl_STORE([STOREID]),
[VOUCHERNUMBER] INT NOT NULL,
[VOUCHERDATE] DATE NOT NULL,
[WARRANTYEXPIREDATE] DATE NOT NULL,
)
GO

CREATE TABLE tbl_ITEM_HISTORY
(
[SINO] VARCHAR(40) CONSTRAINT fk_SI REFERENCES tbl_ITEM_DETAILS([SINO]),
[INSTALLEDLOCATION] VARCHAR(255) NOT NULL,
[INSTALLATIONDATE] DATE NOT NULL,
[ISSUEDTO] VARCHAR(255) NOT NULL,
[CONTACTPERSONNAME] VARCHAR(100) NOT NULL,
[CONTACTDETAILS] INT NULL,
[REPAIRDATE] DATE  NULL,
[REPAIRCODE] INT CONSTRAINT fk_repaircode REFERENCES tbl_REPAIR_STATUS([REPAIRCODE])	,
[REMARKS] VARCHAR(255) NOT NULL,
[HISTORY SHEET] VARCHAR(20) NOT NULL
)
GO



--SELECT * FROM tbl_ITEM_DETAILS
--SELECT * FROM tbl_STORE
--SELECT * FROM tbl_REPAIR_STATUS
--SELECT * FROM tbl_ITEM_HISTORY
